In [1]:
import numpy as np

### NUMPY BASICS

In [2]:
list=[10,20,50,60,70]
x=np.array(list)
x

array([10, 20, 50, 60, 70])

In [3]:
type(x)

numpy.ndarray

In [6]:
matrix=np.array([[5,8,10,11],[9,13,12,15]])
matrix

array([[ 5,  8, 10, 11],
       [ 9, 13, 12, 15]])

### BUILT-IN METHODS AND FUNCTIONS

In [8]:
z=np.random.rand(15)
z

array([0.87100793, 0.3088079 , 0.26233357, 0.63591275, 0.10397001,
       0.08119382, 0.32415314, 0.37217882, 0.33413956, 0.74592247,
       0.05007988, 0.99875585, 0.77439624, 0.11489979, 0.27073689])

In [9]:
y=np.random.rand(5,5)
y

array([[0.06701132, 0.83690259, 0.17776382, 0.12227884, 0.18436161],
       [0.86243492, 0.73715614, 0.09731025, 0.65277029, 0.81750855],
       [0.18402157, 0.40185648, 0.19345374, 0.97306849, 0.4615173 ],
       [0.86295981, 0.00734008, 0.343658  , 0.94844353, 0.37313455],
       [0.48342393, 0.80995913, 0.41507364, 0.71305486, 0.08614579]])

##### randn() - normal distribution between 0 and 1

In [12]:
a=np.random.randn(4,5)
a

array([[-0.86335877,  1.57662303, -0.89055122, -1.03455589,  1.34771463],
       [-1.67170545,  1.19907202, -1.58912651,  0.90559303, -1.15084235],
       [-1.27422706, -0.9254526 ,  0.57839195, -0.11096818,  1.36543968],
       [-1.33450625,  1.63588083, -0.09599774,  0.1591408 ,  0.9990432 ]])

In [15]:
b=np.random.randint(4,10)
b

5

In [17]:
c=np.random.randint(1,100,3)
c

array([66, 71, 41])

In [18]:
d=np.arange(1,10)
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
e=np.arange(1,10,2)
e

array([1, 3, 5, 7, 9])

In [20]:
f=np.eye(10)
f

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
g=np.ones((10,10))
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
h=np.zeros((5,5))
h

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
j=input("Enter a number")
i=np.random.randint(0,j,20)
i

Enter a number8


array([5, 6, 0, 6, 3, 6, 3, 6, 5, 6, 0, 3, 3, 1, 7, 4, 1, 5, 6, 3])

In [25]:
len(i)

20

In [27]:
i.shape

(20,)

In [28]:
i.dtype

dtype('int32')

In [29]:
i.reshape(4,5)

array([[5, 6, 0, 6, 3],
       [6, 3, 6, 5, 6],
       [0, 3, 3, 1, 7],
       [4, 1, 5, 6, 3]])

In [30]:
i.min()

0

In [31]:
i.max()

7

In [33]:
i.argmax()

14

In [35]:
k=np.arange(300,500,10).reshape(4,5)
k

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

In [38]:
l=np.random.randint(-10,10,(2,2))
l

array([[ 7,  5],
       [-8, -3]])

In [39]:
l.max()

7

In [40]:
l.min()

-8

In [41]:
l.mean()

0.25

#### MATH OPERATIONS

In [42]:
m=[1,2,3,4]
n=[1,2,3]
m+n

[1, 2, 3, 4, 1, 2, 3]

In [44]:
o=np.array([1,2,3,4,5])
p=np.array([1,2,3,4,5])
o+p

array([ 2,  4,  6,  8, 10])

In [46]:
np.sqrt(o)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

#### SLICING AND INDEXING

In [58]:
q=np.random.randint(1,15,(3,3))
q

array([[ 6, 12, 13],
       [11, 10, 10],
       [ 3,  9, 12]])

In [59]:
q[0]=100
q

array([[100, 100, 100],
       [ 11,  10,  10],
       [  3,   9,  12]])

In [60]:
q[:2,1:]*=2
q

array([[100, 200, 200],
       [ 11,  20,  20],
       [  3,   9,  12]])

#### ELEMENT SELECTION

In [62]:
r=q[q>12]
r

array([100, 200, 200,  20,  20])

In [65]:
q[q>99]=0
q

array([[ 0,  0,  0],
       [11, 20, 20],
       [ 3,  9, 12]])